import { createServerComponentSupabaseClient } from "@supabase/auth-helpers-nextjs";
import "./globals.css";
import { Inter } from "next/font/google";
import { headers, cookies } from "next/headers";
import SupabaseProvider from "./_components/SupabaseProvder";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const supabase = createServerComponentSupabaseClient({
    headers,
    cookies,
  });

  const {
    data: { session },
  } = await supabase.auth.getSession();
  const {
    data: { user },
  } = await supabase.auth.getUser();

  return (
    <html lang="ja">
      <body className={inter.className}>
        <SupabaseProvider session={session} user={user}>
          <main className="flex flex-col justify-between p-24">{children}</main>
        </SupabaseProvider>
      </body>
    </html>
  );
}
